apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-avis
spec:
  selector:
    matchLabels:
      app: front-avis
  template:
    metadata:
      labels:
        app: front-avis
    spec:
      containers:
      - name: front-avis
        image: chanou41/tp-mern:front10
        env:
        - name: NODE_PORT
          value: "8000"
        - name: NODE_SERVICE
          value: back-service
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front-avis
  ports:
  - port: 80
    targetPort: 80
